SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

EXPLOSION_BASE_DURATION = 30
EXPLOSION_SIZE_MULTIPLIER = 1.5
EXPLOSION_GROWTH_RATIO = 15
EXPLOSION_MIN_SIZE = 10
EXPLOSION_COLOR = (255, 165, 0)

INITIAL_LIVES = 3
RESPAWN_INVULNERABILITY_TIME = 3000
RESPAWN_DELAY = 5

PLAYER_RADIUS = 20

PLAYER_ACCELERATION = 300
PLAYER_SPEED = 500
PLAYER_BRAKE_STRENGTH = 200
PLAYER_REVERSE_ACCELERATION = 150
PLAYER_FRICTION = 1

PLAYER_TURN_SPEED = 300
PLAYER_ROTATION_ACCELERATION = 200
PLAYER_ROTATION_FRICTION = 0.5

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_EXPLOSION_SIZE = 50

SHOT_RADIUS = 5

MULTIPLIER = 1
MULTIPLIER_TIMER = 0
MULTIPLIER_DURATION = 3000
MAX_MULTIPLIER = 5